name: Deploy Poseidon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy Stack
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          STACK_NAME: poseidon
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "poseidon" docker-compose.yml
